updated the testnet description doc [sc-6827]
trisacrypto/trisa pull request #123
Opened 2022-07-07 21:00 UTC by kbelita

[sc-6827](https://app.shortcut.com/rotational/story/6827/trisa-dev-testnet-updates)

* updated description
* changed shortcode link pointing to TestNet architecture image to markdown image.

2022-07-08 21:58 UTC, eschmier requested changes
Looks good @kbelita ! Thank you for giving attention to this page. I fixed a few small typos and revised a sentence.

2022-07-08 21:58 UTC, eschmier commented on docs/content/testnet/_index.en.md
> +2. Complete the  multi-part VASP Verification form and due diligence process. Once approved, you gain will gain to the TestNet.
Typo: "Once approved, you will gain access to the TestNet."

2022-07-08 21:58 UTC, eschmier commented on docs/content/testnet/_index.en.md
> +3. Set up your TRISA node or integrate with a 3rd-party solution to start testing. When considering setting up your own server to host your own TRISA node, you must consider items necessary that may
Reworded slightly plus fixed typo: "Set up your TRISA node or integrate with a 3rd-party solution to start testing. When considering setting up your own server to host your own TRISA node, you must consider resources necessary that may incur costs such as the server itself, a long-term data storage solution, and developer time to configure and test.

2022-07-08 21:58 UTC, eschmier commented on docs/content/testnet/_index.en.md
> +![TestNet Architecture](/img/testnet_architecture.png)
I wasn't able to see the image file so can't tell if it works.

2022-07-09 20:28 UTC, rebeccabilbro approved these changes
Looks great @kbelita and thank you @eschmier for the helpful feedback!

2022-07-09 20:30 UTC, merged